name: Update README feeds

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-feeds:
    name: Update README with Medium posts and YouTube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Latest Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@alok.ch83"
          max_post_count: "5"
          comment_tag_name: "BLOG-POST-LIST"

      - name: Latest Worth Knowing TV videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCfz9mdRrU1xabf44sstW8Cg"
          max_post_count: "4"
          comment_tag_name: "YOUTUBE-LIST"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<table><tr><td><a href="$url"><img width="160px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg" alt="$title"/></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
